# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('desc', models.TextField(default='', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Todo task',
                'verbose_name_plural': 'Task list',
                'managed': True,
            },
        ),
    ]
